# Generated by Django 6.0.6 on 2026-06-24 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField(max_length=500)),
                ('response_length', models.IntegerField(default=0, help_text='Longueur de la réponse en caractères')),
                ('response_time_ms', models.IntegerField(default=0, help_text='Temps de réponse en millisecondes')),
                ('tokens_used', models.IntegerField(default=0)),
                ('tool_called', models.CharField(blank=True, help_text="Nom de l'outil utilisé", max_length=50)),
                ('action_success', models.BooleanField(help_text="L'action demandée a-t-elle réussi ?", null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Métrique agent IA',
                'verbose_name_plural': 'Métriques agent IA',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConversationChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('multi', 'Agent Multi-Rôles')], default='multi', max_length=30)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant IA'), ('system', 'Système')], max_length=10)),
                ('contenu', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_agent.conversationchat')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
