# Generated by Django 5.2.15 on 2026-07-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmetric',
            name='rag_chunks',
            field=models.IntegerField(default=0, help_text='Nombre de chunks injectés dans le prompt'),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='rag_top_score',
            field=models.FloatField(blank=True, help_text='Score du meilleur chunk retrouvé', null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='retrieval_ms',
            field=models.IntegerField(default=0, help_text='Latence du retrieval en millisecondes'),
        ),
    ]
