# Generated by Django 6.0.6 on 2026-06-24 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('credits', models.IntegerField(default=3)),
                ('coefficient', models.FloatField(default=1.0)),
                ('heures_cours', models.IntegerField(default=0)),
                ('heures_td', models.IntegerField(default=0)),
                ('heures_tp', models.IntegerField(default=0)),
                ('semestre', models.IntegerField(choices=[(1, 'S1'), (2, 'S2')])),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='administration.filiere')),
            ],
            options={
                'ordering': ['filiere', 'semestre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jour', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_seance', models.CharField(choices=[('cours', 'Cours'), ('td', 'TD'), ('tp', 'TP')], max_length=10)),
                ('annee_universitaire', models.CharField(default='2024-2025', max_length=9)),
                ('semestre', models.IntegerField(choices=[(1, 'S1'), (2, 'S2')])),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='administration.classe')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.enseignant')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.salle')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.matiere')),
            ],
            options={
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='MoyenneEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_universitaire', models.CharField(default='2024-2025', max_length=9)),
                ('semestre', models.IntegerField(choices=[(1, 'S1'), (2, 'S2')], default=1)),
                ('moyenne', models.FloatField(blank=True, null=True)),
                ('mention', models.CharField(blank=True, choices=[('', '—'), ('passable', 'Passable (10–12)'), ('assez_bien', 'Assez Bien (12–14)'), ('bien', 'Bien (14–16)'), ('tres_bien', 'Très Bien (16–18)'), ('excellent', 'Excellent (18–20)')], max_length=20)),
                ('admis', models.BooleanField(default=False)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='administration.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='administration.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_note', models.CharField(choices=[('ds', 'DS'), ('exam', 'Examen'), ('tp', 'TP'), ('expose', 'Exposé'), ('rattrapage', 'Rattrapage')], max_length=15)),
                ('note', models.FloatField()),
                ('annee_universitaire', models.CharField(max_length=9)),
                ('semestre', models.IntegerField(choices=[(1, 'S1'), (2, 'S2')])),
                ('date_saisie', models.DateField(auto_now_add=True)),
                ('saisie_par', models.CharField(blank=True, max_length=100)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.enseignant')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='administration.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('justifiee', models.BooleanField(default=False)),
                ('motif', models.TextField(blank=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='administration.etudiant')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.emploidutemps')),
            ],
            options={
                'indexes': [models.Index(fields=['etudiant', 'date'], name='pedagogie_a_etudian_fdf0df_idx')],
                'unique_together': {('etudiant', 'seance', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='matiere',
            index=models.Index(fields=['filiere', 'semestre'], name='pedagogie_m_filiere_8b6b43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moyenneetudiant',
            unique_together={('etudiant', 'classe', 'annee_universitaire', 'semestre')},
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['etudiant', 'semestre', 'annee_universitaire'], name='pedagogie_n_etudian_97cc8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('etudiant', 'matiere', 'type_note', 'annee_universitaire', 'semestre')},
        ),
    ]
