# Generated by Django 6.0.6 on 2026-06-24 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(choices=[('mathematiques', 'Mathématiques'), ('informatique', 'Informatique'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('biologie', 'Biologie'), ('geologie', 'Géologie')], max_length=50, unique=True)),
                ('chef', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50)),
                ('type_salle', models.CharField(choices=[('amphi', 'Amphithéâtre'), ('salle', 'Salle de Cours'), ('tp', 'Salle TP'), ('info', 'Salle Informatique')], max_length=10)),
                ('capacite', models.IntegerField()),
                ('batiment', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('Doc', 'Doctorat'), ('CPI', 'CPI'), ('CI', 'CI Ingénieur')], max_length=5)),
                ('type_formation', models.CharField(choices=[('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('cpi', 'CPI'), ('ci', 'CI')], default='licence', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='administration.departement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero_etudiant', models.CharField(max_length=20, unique=True)),
                ('cin', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('annee_inscription', models.IntegerField()),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('suspendu', 'Suspendu'), ('diplome', 'Diplômé'), ('abandonne', 'Abandonné')], default='inscrit', max_length=20)),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='administration.filiere')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('niveau', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2'), ('Doc1', 'Doc1'), ('Doc2', 'Doc2'), ('Doc3', 'Doc3'), ('CPI1', 'CPI1'), ('CPI2', 'CPI2'), ('CI1', 'CI1'), ('CI2', 'CI2'), ('CI3', 'CI3')], max_length=10)),
                ('annee_universitaire', models.CharField(default='2024-2025', max_length=9)),
                ('capacite', models.IntegerField(default=30)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='administration.filiere')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_universitaire', models.CharField(default='2024-2025', max_length=9)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('dossier_incomplet', 'Dossier incomplet'), ('frais_non_payes', 'Frais non payés'), ('validee', 'Validée'), ('suspendue', 'Suspendue'), ('annulee', 'Annulée')], default='en_attente', max_length=25)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('valide_par', models.CharField(blank=True, default='', max_length=100)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='administration.etudiant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.filiere')),
            ],
            options={
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VALIDATE', 'Validation'), ('REJECT', 'Rejet'), ('STATUS_CHANGE', 'Changement de statut'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('EXPORT', 'Export de données')], db_index=True, max_length=20)),
                ('model_name', models.CharField(db_index=True, max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text="Utilisateur qui a effectué l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='administrat_model_n_ad7686_idx'), models.Index(fields=['user', 'timestamp'], name='administrat_user_id_c8fb85_idx')],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('grade', models.CharField(choices=[('assistant', 'Assistant'), ('maitre_assistant', 'Maître Assistant'), ('maitre_conf', 'Maître de Conférences'), ('professeur', 'Professeur')], max_length=30)),
                ('specialite', models.CharField(blank=True, max_length=100)),
                ('date_recrutement', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='administration.departement')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['matricule'], name='administrat_matricu_b6995e_idx'), models.Index(fields=['departement', 'actif'], name='administrat_departe_61c043_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['numero_etudiant'], name='administrat_numero__4b530e_idx'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['email'], name='administrat_email_e229f2_idx'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['statut', 'annee_inscription'], name='administrat_statut_699f24_idx'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['filiere', 'statut'], name='administrat_filiere_5c58e0_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['statut', 'annee_universitaire'], name='administrat_statut_c982f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('etudiant', 'annee_universitaire')},
        ),
    ]
