# Generated by Django 6.0.6 on 2026-06-24 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_diplome', models.CharField(max_length=50)),
                ('specialite', models.CharField(max_length=100)),
                ('annee_obtention', models.IntegerField()),
                ('mention', models.CharField(blank=True, choices=[('passable', 'Passable'), ('assez_bien', 'Assez Bien'), ('bien', 'Bien'), ('tres_bien', 'Très Bien')], max_length=20)),
                ('moyenne_generale', models.FloatField(blank=True, null=True)),
                ('numero_diplome', models.CharField(max_length=50, unique=True)),
                ('date_delivrance', models.DateField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='administration.etudiant')),
            ],
            options={
                'ordering': ['-annee_obtention'],
            },
        ),
        migrations.CreateModel(
            name='DemandeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_stage', models.CharField(choices=[('observation', 'Stage Observation'), ('initiation', 'Stage Initiation'), ('pfe', 'PFE')], max_length=20)),
                ('entreprise', models.CharField(max_length=200)),
                ('sujet', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('encadrant_entreprise', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En Attente'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('en_cours', 'En Cours'), ('termine', 'Terminé')], default='en_attente', max_length=15)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('rapport', models.FileField(blank=True, null=True, upload_to='rapports_stage/')),
                ('note_stage', models.FloatField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('encadrant_fsb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_encadres', to='administration.enseignant')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='administration.etudiant')),
            ],
            options={
                'ordering': ['-date_demande'],
                'indexes': [models.Index(fields=['statut', 'type_stage'], name='stages_dema_statut_ca960b_idx')],
            },
        ),
    ]
